'use client';
import './globals.css';
// import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import Layout from '@/layout/Layout';
import { ThemeProvider } from 'next-themes';
const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${inter.className} dark:bg-[#1a202c] bg-[#eee]`}>
				<ThemeProvider attribute='class'>
					<Layout>{children}</Layout>
				</ThemeProvider>
			</body>
		</html>
	);
}
